My First Program in R

1.Print

In [20]:
print("Hello World")
cat("R","program")

[1] "Hello World"
R program

2.Variables and Data Types

In [21]:
myString <- "I love programming"
wholeNum <- 12
floatingNum <- 1.2
isBool <- TRUE


print(wholeNum)
print(myString)
print(floatingNum)
print(isBool)
class(isBool)

[1] 12
[1] "I love programming"
[1] 1.2
[1] TRUE

[1] "logical"

3.Numerical Operators

In [22]:
x <-10
y <- 3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y
mod <- x %% y
exp <- x ^ y


print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1
[1] 1000

4.User Input

In [26]:
name <- readline("Enter name: ")
cat("My name is:",name)

Enter name: aaron
My name is:  aaron

5.Decision Making

In [30]:
grade <- 90
if (grade < 75){
  print("You failed")
}else{
  print("You passed")
}

[1] "You passed"

6.Loop

In [38]:
for (i in 1:10){
  cat("\n",i)
}

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10

7.Function

In [39]:
addNumber <- function(a,b){
  return(a+b)

}
addNumber(1,1)

[1] 2

8.Vectors

In [42]:
grades <- c(98,76,87,86,99)
grades

mean(grades)
max(grades)
min(grades)
length(grades)
median(grades)
summary(grades)

[1] 98 76 87 86 99

[1] 89.2

[1] 99

[1] 76

[1] 5

[1] 87

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   76.0    86.0    87.0    89.2    98.0    99.0

9.Matrices

In [47]:
matrix(c(1,2,3,4,5,6),nrow=2)

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10.Lists

In [50]:
students <- list(
  name = "Aaron",
  course = "BSCS",
  grade = 88
)

students

$name
[1] "Aaron"

$course
[1] "BSCS"

$grade
[1] 88

11.DataFrame

In [54]:
students <- data.frame(
  name = c("Aaron","Jim","Cueto"),
  course = c("BSCS","BSIT","BSA"),
  grade = c(75,77,90)
)
students

  name  course grade
1 Aaron BSCS   75
2 Jim   BSIT   77
3 Cueto BSA    90

12.Write to CSV

In [55]:
#save dataframe
write.csv(students,"students.csv")

13.Read CVS File

In [59]:
data <- read.csv("students.csv")
head(data)
summary(data)

  X name  course grade
1 1 Aaron BSCS   75
2 2 Jim   BSIT   77
3 3 Cueto BSA    90

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :75.00
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:76.00
 Median :2.0   N.blank  :0   N.blank  :0   Median :77.00
 Mean   :2.0   Min.nchar:3   Min.nchar:3   Mean   :80.67
 3rd Qu.:2.5   Max.nchar:5   Max.nchar:4   3rd Qu.:83.50
 Max.   :3.0                               Max.   :90.00